on:
  push:

env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fyscience

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Build image from cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: erkannt/wissenschaftsbefreiungsfront/freeyourscience
          image_tag: ${{ github.sha }}
          registry: docker.pkg.github.com
          username: erkannt
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Tag Container Images
        run: |
          docker tag my_awesome_image:latest $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}
          docker build --cache-from my_awesome_image:latest -t dev .

      - name: Test
        run: |
          docker run dev black --check
          docker run dev pytest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Push Image
        run: |
          gcloud auth configure-docker gcr.io
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud components install beta
          gcloud beta run deploy "${{ secrets.GCP_CLOUDRUN_SERVICE_DEV }}" \
            --image "$IMAGE_NAME:${{ github.sha }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "UNPAYWALL_EMAIL=${{ secrets.API_EMAIL }},SHERPA_API_KEY=${{ secrets.SHERPA_API_KEY }},S2_API_KEY=${{ secrets.S2_API_KEY }}" \
            --revision-suffix ${{ github.sha }}
