on:
  push:

env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fyscience

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Test
        run: |
          pip3 install .[dev]
          black --check
          pytest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Image
        run: |
          gcloud auth configure-docker gcr.io
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud components install beta
          gcloud beta run deploy "${{ secrets.GCP_CLOUDRUN_SERVICE }}" \
            --image "$IMAGE_NAME:${{ github.sha }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars UNPAYWALL_EMAIL=${{ secrets.API_EMAIL }},SHERPA_API_KEY=${{ secrets.SHERPA_API_KEY }},S2_API_KEY=${{ secrets.S2_API_KEY }},GUNICORN_CMD_ARGS="--secure-scheme-headers \"{'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}\""
