on:
  push:
    tags:
      - "latest/*"

env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fyscience

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        run: |
          gcloud components install beta
          gcloud beta run deploy "${{ secrets.GCP_CLOUDRUN_SERVICE }}" \
            --image "$IMAGE_NAME:${{ github.sha }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "UNPAYWALL_EMAIL=${{ secrets.API_EMAIL }},SHERPA_API_KEY=${{ secrets.SHERPA_API_KEY }},S2_API_KEY=${{ secrets.S2_API_KEY }}" \
            --revision-suffix ${{ github.sha }}
